image: openjdk:21-jdk-slim  # Usa una imagen base con Java 21

services:
  - name: mariadb:10.7
    alias: db  # Nombre de host para MariaDB
    variables:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jaapec_tenant_service
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpasss

  - name: rabbitmq:3-management
    alias: rabbitmq  # Nombre de host para RabbitMQ
    variables:
      RABBITMQ_DEFAULT_USER: kcrqwise
      RABBITMQ_DEFAULT_PASS: I3SCFxjoQT8zExp7vrx6k5Xr9uOaGx6a
      RABBITMQ_DEFAULT_VHOST: kcrqwise

variables:
  DATABASE_HOST: db
  DATABASE_PORT: 3306
  DATABASE_NAME: jaapec_tenant_service
  DATABASE_USER: dbuser
  DATABASE_PASSWORD: dbpasss
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_LOGIN: kcrqwise
  RABBITMQ_PASSWORD: I3SCFxjoQT8zExp7vrx6k5Xr9uOaGx6a
  RABBITMQ_VHOST: kcrqwise

stages:
  - test

integration-tests:
  stage: test
  script:
    - apt update
    - apt install nmap -y
    - nmap db -p 3306
    - chmod +x gradlew
    - ./gradlew test
