image: openjdk:21-jdk-slim

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DATABASE_HOST: db
  DATABASE_PORT: 3306
  DATABASE_NAME: jaapec_tenant_service
  DATABASE_USER: dbuser
  DATABASE_PASSWORD: dbpasss
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_LOGIN: kcrqwise
  RABBITMQ_PASSWORD: I3SCFxjoQT8zExp7vrx6k5Xr9uOaGx6a
  RABBITMQ_EXCHANGE: domain_events
  RABBITMQ_MAX_RETRIES: 5
  RABBITMQ_VHOST: kcrqwise

stages:
  - test

test:
  stage: test
  image: openjdk:21-jdk-slim
  services:
    - name: mariadb:10.7
      alias: db
    - name: rabbitmq:3-management
      alias: rabbitmq
  script:
    - apt-get update && apt-get install -y mariadb-client curl
    - mysql -h db -u"$DATABASE_USER" -p"$DATABASE_PASSWORD" -e "SELECT 1;"
    - curl -s -u "$RABBITMQ_LOGIN:$RABBITMQ_PASSWORD" "http://rabbitmq:15672/api/healthchecks/node"
    - chmod +x gradlew
    - ./gradlew test
  artifacts:
    reports:
      junit: build/test-results/test/*.xml