spring.application.name=tenant-service
server.port=8080
spring.graphql.graphiql.enabled=true
logging.level.root=info
logging.file.name=var/log/application.log
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false
spring.messages.cache-duration=3600

