spring.application.name=users-service
server.port=8080
spring.graphql.graphiql.enabled=true
logging.level.root=info
logging.file.name=var/log/application.log
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
